version: 1
services:
  - type: web
    name: github-profile-stats
    env: go
    buildCommand: cd backend && go build -o main .
    startCommand: cd backend && ./main
    envVars:
      - key: GITHUB_TOKEN
        fromSecret: TOKEN_API
      - key: PORT
        value: 10000
