version: 1
services:
  - type: web
    name: github-profile-stats
    env: go
    buildCommand: go build -o main .
    startCommand: ./main
    envVars:
      - key: GITHUB_TOKEN
        fromSecret: TOKEN_API
