services:
  - type: web
    name: github-stats-api
    env: go
    buildCommand: go build -o main .
    startCommand: ./main
    plan: free
    autoDeploy: true
    envVars:
      - key: TOKEN_API
        value: ${TOKEN_API}

  - type: web
    name: github-stats-frontend
    env: static
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    plan: free
    autoDeploy: true
