version: 1
services:
  - type: web
    name: github-stats-backend
    env: go
    buildCommand: go build -o backend ./backend
    startCommand: ./backend
    plan: free
    envVars:
      - key: TOKEN_API
        fromSecret: TOKEN_API
    routes:
      - type: forward
        path: /backend
        service: github-stats-backend
